### ISSUE TITLE
Config will not load

### ISSUE THREAD

**Issue by StabbyMcGhost** [Qbox-project/qbx_apartments#15]
### Summary

When server starts config fails to load.

### Reproduction

--TX ADMIN--

[    c-scripting-core] Failed to load script @qb-apartments/config.lua.

--F8 Log--

[   7792203] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @qbx-apartments/client/main.lua:359: attempt to index a nil value (field 'enter')^7
[   7792203] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@qbx-apartments/client/main.lua^7:359)
[   7800875] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @qbx-apartments/client/main.lua:99: attempt to index a nil value (field 'enter')^7
[   7800875] [b2699_GTAProce]             MainThrd/ ^3> createEntrances^7 (^5@qbx-apartments/client/main.lua^7:99)
[   7800875] [b2699_GTAProce]             MainThrd/ ^3> loggedIn^7 (^5@qbx-apartments/client/main.lua^7:283)
[   7800875] [b2699_GTAProce]             MainThrd/ ^3> ref^7 (^5@qbx-apartments/client/main.lua^7:446)

### Expected behavior

Expect it to start

### Actual behavior

Failed to start 

### Last Updated

Today see if it would fix it.

### Custom Resources

spooner

### Resource Rename

no

**Comment by MafewTM** [comment]
Does this still appear to be an issue with the latest version?
